blueprint:
  name: Deconz - Philips Hue Dimmer Switch Config - V2023.02.07
  description: |
    Control lights with a Philips Hue Dimmer Switch (only RWL020 (US) and RWL021 (EU), RWL022, the one that says 'hue' on the bottom, has a different button layout.)
    
    This blueprint is a simplified version of stefanroelofs's `ZHA - Philis Hue Dimmer Switch V2', but this one has no default inputs and with full configuration available. This makes the remote easily configurable for purposes other than controlling lights.
    
    If you are intending to just use it for use as a light switch, I recommend using his blueprint, which you can find at https://gist.github.com/stefanroelofs/775e2e0a3cdb3d72a9451fb247492d59
    
    It includes customizable 'on' button behaviour and default setup of the dimmer buttons to dim as they normally would. To make the configuration available for other automations, I had to remove these very useful functionalities.
    
    Please note that the Philips Hue Dimmer Switch also supports triple, quadruple, and even quintuple button presses. It's fairly easy to configure these yourself by editing this blueprint.
    
    Please also note that I am not much good at python and therefore probably cannot help you if this does not work. All credit for figuring out how all this works goes to stefanroelofs, vanstinator and warriorrocker. I just adapted their work to make the dimming buttons free to execute other actions. 
    
    Does this blueprint not work for you? Did you add your Hue dimmer to ZHA before July 2020?
    It might help to press the 'Reconfigure device' button on the ZHA Device info page.
    The naming of the command attribute in the zha_event was changed back then. 
  domain: automation
  source_url: https://github.com/mspearey/ha-blueprints/hue/dimmer/HueDimmer-Deconz.yaml

  # Define the inputs for the blueprint
  input:
    remote:
      name: Philips Hue Dimmer Switch
      description: Pick either RWL020 (US) or RWL021 (EU)
      selector:
        device:
          integration: deconz
          manufacturer: Philips
          entity:
            domain: sensor
            device_class: battery
# inputs for custom actions
    button_on_short_press:
      name: On button short press
      description: Action to run on short on button press.
      default: []
      selector:
        action:
    button_on_long_press:
      name: On button long press
      description: Action to run on long on button press.
      default: []
      selector:
        action:
    button_on_short_release:
      name: On button short release
      description: Action to run on short on button release.
      default: []
      selector:
        action:
    button_on_long_release:
      name: On button long release
      description: Action to run on long on button release.
      default: []
      selector:
        action:
        
    button_up_short_press:
      name: Up button short press
      description: Action to run on short up button press.
      default: []
      selector:
        action:
    button_up_long_press:
      name: Up button long press
      description: Action to run on long up button press.
      default: []
      selector:
        action:
    button_up_short_release:
      name: Up button short release
      description: Action to run on short up button release.
      default: []
      selector:
        action:
    button_up_long_release:
      name: Up button long release
      description: Action to run on long up button release.
      default: []
      selector:
        action:
        
    button_down_short_press:
      name: Down button short press
      description: Action to run on short down button press.
      default: []
      selector:
        action:
    button_down_long_press:
      name: Down button long press
      description: Action to run on long down button press.
      default: []
      selector:
        action:
    button_down_short_release:
      name: Down button short release
      description: Action to run on short down button release.
      default: []
      selector:
        action:
    button_down_long_release:
      name: Down button long release
      description: Action to run on long down button release.
      default: []
      selector:
        action:
        
    button_off_short_press:
      name: Off button short press
      description: Action to run on short off button press.
      default: []
      selector:
        action:
    button_off_long_press:
      name: Off button long press
      description: Action to run on long off button press.
      default: []
      selector:
        action:
    button_off_short_release:
      name: Off button short release
      description: Action to run on short off button release.
      default: []
      selector:
        action:
    button_off_long_release:
      name: Off button long release
      description: Action to run on long off button release.
      default: []
      selector:
        action:

mode: restart
max_exceeded: silent

# Trigger the automation when the selected dimmer remote sends an event
trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      device_id: !input remote

action:
  - variables:
      event: '{{ trigger.event.data.event }}'

  - choose:
    - conditions: '{{ event == 1000 }}'
      sequence: !input button_on_short_press

    - conditions: '{{ event == 1001 }}'
      sequence: !input button_on_long_press

    - conditions: '{{ event == 1002 }}'
      sequence: !input button_on_short_release

    - conditions: '{{ event == 1003 }}'
      sequence: !input button_on_long_release


    - conditions: '{{ event == 4000 }}'
      sequence: !input button_off_short_press

    - conditions: '{{ event == 4001 }}'
      sequence: !input button_off_long_press

    - conditions: '{{ event == 4002 }}'
      sequence: !input button_off_short_release

    - conditions: '{{ event == 4003 }}'
      sequence: !input button_off_long_release


    - conditions: '{{ event == 2000 }}'
      sequence: !input button_up_short_press

    - conditions: '{{ event == 2001 }}'
      sequence: !input button_up_long_press

    - conditions: '{{ event == 2002 }}'
      sequence: !input button_up_short_release

    - conditions: '{{ event == 2003 }}'
      sequence: !input button_up_long_release


    - conditions: '{{ event == 3000 }}'
      sequence: !input button_down_short_press

    - conditions: '{{ event == 3001 }}'
      sequence: !input button_down_long_press

    - conditions: '{{ event == 3002 }}'
      sequence: !input button_down_short_release

    - conditions: '{{ event == 3003 }}'
      sequence: !input button_down_long_release